### PR TITLE
Replaced method of getting userAgent from deprecated UIWebView

### PR DESCRIPTION
**Pull request by shnaz**
- Replaced method of getting userAgent from UIWebView (which is deprecated)
- Included app name in UA

### CODE REVIEW

**Comment by KSemenenko** [comment]
Hi @shnaz , thank you so much for your PR.
UserAgent was needed in order for GoogleAnalyctics mola to build reports on mobile devices.
Are you sure that adding a name application will not break it?

**Comment by shnaz** [comment]
Hi @KSemenenko I am not sure about how they would do that, tbh.

**Comment by shnaz** [comment]
@KSemenenko Do you have an alternative solution? I have tried with WKWebView, but the problem is that it has to be added as subview somewhere before it is able to evaluate anything, besides that EvaluateJavaScript is now async which makes it difficult to work in the current implementation of DeviceInfo.

**Comment by vmelia** [comment]
This issue is somewhat urgent since Apple will reject apps that link in UIWebView before the end of the year.

[https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/webview?tabs=macos#uiwebview-deprecation-and-app-store-rejection-itms-90809](url)

**Comment by wcoder** [comment]
@KSemenenko 
Could you please check this PR? or publish new nuget versions with fix
Because now this issue is blocker:

https://developer.apple.com/news/?id=12232019b

**Comment by KSemenenko** [comment]
@wcoder Thanks a lot!

**Pull request merged**
